# Generated by Django 5.0.3 on 2024-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms', models.CharField(blank=True, max_length=100, null=True)),
                ('parking', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('metr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
